### ISSUE TITLE
how to use with associative array

### ISSUE THREAD

**Issue by ghost** [caleb-tolu/react-native-multiple-tags#3]
How to use react-native-multiple-tags with associative array.
Example 
      "data": [
        {
            "Id": "9",
            "Name": "A"
        },
        {
            "Id": "10",
            "Name": "B"
        },
        {
            "Id": "11",
            "Name": "C"
        }
    ]

At submit button, i want to save corresponding ID also. Please explain, how to use multiple-tags using array id  and name

**Comment by tolucaleb** [comment]
this package does not support arrays of objects for now, it only supports arrays of items or tags, but i think i will just have to add the support very soon.

**Comment by tolucaleb** [comment]
closing this issue now since the package can now be used with associative array or array of objects
